name: Retail Data Pipeline CI

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

jobs:

  test:

    name: Run PyTest

    runs-on: ubuntu-latest

    steps:

      # ----------------------------------------------------
      # 1. Checkout repository
      # ----------------------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v5

      # ----------------------------------------------------
      # 2. Setup Python
      # ----------------------------------------------------

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ----------------------------------------------------
      # 3. Setup Java for PySpark
      # ----------------------------------------------------

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      # ----------------------------------------------------
      # 4. Upgrade pip
      # ----------------------------------------------------

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      # ----------------------------------------------------
      # 5. Install project dependencies
      # ----------------------------------------------------

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # ----------------------------------------------------
      # 6. Run automated tests
      # ----------------------------------------------------

      - name: Run PyTest
        run: |
          python -m pytest tests -v